### ISSUE TITLE
Possible security improvement in gem push task "Harden Runner" section

### ISSUE THREAD

**Issue by keithrbennett** [rubygems/configure_trusted_publisher#17]
I ran `gem exec configure_trusted_publisher rubygem` on my gem, and saw a suggestion on the task monitoring web site to slightly modify the "Harden Runner" section of the workflow specification for improved security...

From:

```yaml
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit
```

To:

```yaml
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            index.rubygems.org:443
            objects.githubusercontent.com:443
            rubygems.org:443
```

Might this be a better configuration to generate? I would be happy to offer a pull request if that would be helpful.
