### ISSUE TITLE
Action skipped if your source_code_uri is in the form of https://github.com/<org>/<repo>.git

### ISSUE THREAD

**Issue by technicalpickles** [rubygems/configure_trusted_publisher#5]
I had this in my gemspec:

```ruby
Gem::Specification.new do |spec|
  # ...
  spec.homepage = "https://github.com/rubyatscale/singed"
  spec.metadata = {
    "source_code_uri" => "https://github.com/rubyatscale/singed.git",
    "bug_tracker_uri" => "https://github.com/rubyatscale/singed/issues",
    "homepage_uri" => "https://github.com/rubyatscale/singed"
  }
  # ... 
end
```

Semantically, I'm not sure if the source code URI is intended to be clonable or not, so I used 

This ended up generating this workflow YAML which never evaluates to true:

```
jobs:
  push:
    if: github.repository == 'rubyatscale/singed.git'
    runs-on: ubuntu-latest
```

That resulted in the workflow being "skipped"
