### ISSUE TITLE
Version bump with workflow call

### ISSUE THREAD

**Issue by excid3** [rubygems/configure_trusted_publisher#7]
One addition that would be helpful is being able to bump the version number along with the release.

Here's an example implementation I made with GitHub Actions that accepts the version as a String input in the Actions UI on the web for reference:

```yaml
name: Publish Gem
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        type: string

jobs:
  test:
    uses: ./.github/workflows/ci.yml

  push:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
   
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby

      - name: Update version
        run: |
          sed -i 's/".*"/"${{ inputs.version }}"/' lib/noticed/version.rb
          bundle config set --local deployment 'false'
          bundle
          bundle exec appraisal
          git config user.name 'GitHub Actions'
          git config user.email github-actions@github.com
          git add Gemfile.lock gemfiles lib
          git commit -m "Version bump"
          git push

      - uses: rubygems/release-gem@v1
```
